version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: 8.4
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: unless-stopped 
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  php:
    build:
      context: ./docker/php
      args:
        php_version: 8.2-apache
    container_name: docker-php
    ports:
      - "8100:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
